export const AUTH_STARTED = "AUTH_STARTED";
export const AUTH_SUCCEEDED = "AUTH_SUCCEEDED";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";

export const UPDATE_USER_STARTED = "UPDATE_USER_STARTED";
export const UPDATE_USER_SUCCEEDED = "UPDATE_USER_SUCCEEDED";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const SET_REDIRECT_ROUTE = "SET_REDIRECT_ROUTE";

export const CLEAR_SUCCESS_MESSAGE_ADS = "CLEAR_SUCCESS_MESSAGE_ADS";
export const CLEAR_SUCCESS_MESSAGE_PROFILE = "CLEAR_SUCCESS_MESSAGE_PROFILE";
