export const AUTH_STARTED = "AUTH_STARTED";
export const AUTH_SUCCEEDED = "AUTH_SUCCEEDED";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";

export const USER_STARTED = "USER_STARTED";
export const USER_SUCCEEDED = "USER_SUCCEEDED";
export const USER_FAILED = "USER_FAILED";
export const USER_CLEAR_ERROR = "USER_CLEAR_ERROR";

export const SET_REDIRECT_ROUTE = "SET_REDIRECT_ROUTE";

export const CLEAR_SUCCESS_MESSAGE_USER = "CLEAR_SUCCESS_MESSAGE_USER";
